### ISSUE TITLE
Undifined output after fetch data from api

### ISSUE THREAD

**Issue by ariebrainware** [ariebrainware/learnNodeJS#1]
https://github.com/ariebrainware/learnNodeJS/blob/890583af7d94e783dc51c8dc18c0ccf907cdcaf6/index.js#L34-L39

I follow from [this url](https://www.npmjs.com/package/node-fetch)  to use fetch in nodejs
@michaeltamsil @mhaidarh

**Comment by michaeltamsil** [comment]
https://github.com/ariebrainware/learnNodeJS/blob/890583af7d94e783dc51c8dc18c0ccf907cdcaf6/index.js#L31-L33
change to
`.then( response => response.toJSON() )`

or
 
`.then( response => { 
    return response.toJSON()
})`

i've already tried & this is the result
![screenshot from 2018-08-01 16-18-04](https://user-images.githubusercontent.com/1217299/43512944-9df9317a-95a6-11e8-9883-e4b9aaccd72b.png)

**Comment by ariebrainware** [comment]
```return response.json()``` or ```return response.toJSON()``` ??

**Comment by michaeltamsil** [comment]
just pick one .... it's same

**Comment by ariebrainware** [comment]
ok .. it work correctly 
![screenshot from 2018-08-01 16-25-35](https://user-images.githubusercontent.com/26453961/43513276-89caa854-95a7-11e8-86f8-83752f7ba95f.png)

thanks @michaeltamsil  :+1:
